Repository crate/croud, pull requests merged in 2020-07, with the labels that each got.

#285 Upgrade to docs build 0.3.0
  .github/CODEOWNERS
  .gitignore
  DEVELOP.rst
  docs/Makefile
  docs/build.json
  docs/utils.json
Labels: documentation, meta

#286 Add eks1.eu-west-1.aws region to documentation
  docs/commands/regions.rst
Labels: ready-to-merge

#287 Upgrade to docs build 0.3.1
  .gitignore
  .readthedocs.yml
  DEVELOP.rst
  docs/Makefile
  docs/build.json
  docs/requirements.txt
Labels: blocked, documentation, meta
